name: Build and Package PostgreSQL

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual execution

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out PostgreSQL Repository
        uses: actions/checkout@v2

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper devscripts fakeroot bash

      - name: Build PostgreSQL
        run: |
          pwd
          cd /home/runner/work/postgres-mirror/postgres-mirror
          pwd
          ./configure
          make
        working-directory: /home/runner/work/postgres-mirror/postgres-mirror

      - name: initdb and start the postgresql server
        run: |
          pwd
          ls
          cd /home/runner/work/postgres-mirror/postgres-mirror
          pwd        working-directory: /home/runner/work/postgres-mirror/postgres-mirror

    
